upscale_timedomains={
'T6HMN':'Mean over 30 days sampled every 6 hours',
'T24H0Z':'Instantaneous values at 0Z every 24 hours',
'T6H':'Instantaneous values at 6 hourly intervals starting at 0Z',
'T6HDAYM':'Daily mean of values sampled every 6 hours',
'TDAYM':'Daily mean, sampled each timestep',
'TDAYMAX':'Daily maximum of timestep data',
'TDAYMIN':'Daily minimum of timestep data',
'TMONMN':'Monthly mean data sampled every timestep',
'T30DAY':'Instantaneous values output once every 30 days',
'TMPMN00':'Monthly mean of values at 0Z (for diurnal cycle)',
'TMPMN03':'Monthly mean of values at 3Z',
'TMPMN06':'Monthly mean of values at 6Z',
'TMPMN09':'Monthly mean of values at 9Z',
'TMPMN12':'Monthly mean of values at 12Z',
'TMPMN15':'Monthly mean of values at 15Z',
'TMPMN18':'Monthly mean of values at 18Z',
'TMPMN21':'Monthly mean of values at 21Z',
'T3HDAYM':'Daily mean sampled every 3 hours',
'T6HRMAX':'Maximum value of timestep data in each 6 hour period',
'T3H':'Instantaneous values every 3 hours from 0Z',
'T3HMN':'3 hourly means of timestep data',
}
